#Browser SELECTION
browser = chrome
#URL SELECTION
url= https://www.naukri.com/nlogin/login
#APPLICATION LOGIN DETAIL
username= solusingh251@gmail.com
password= Amitesh@098
#locations
startReport = C:\\Users\\amite\\eclipse-workspace\\Naukari\\Reports
endReport = C:\\Users\\amite\\eclipse-workspace\\Naukari\\Reports\\index.html
excelPath = C:\\Users\\amite\\eclipse-workspace\\Naukari\\src\\test\\resources\\Excel.xlsx
resumePath = C:\\Users\\amite\\Downloads\\Amitesh_Singh_QA_Resume